export const Actions = {
    // PAGE_LOGIN: 'PAGE_LOGIN',
    // PAGE_SIGNUP: 'PAGE_SIGNUP',
    // PAGE_CHAT: 'PAGE_CHAT',
    CHANGE_CURRENT_CONVERSATION: 'CHANGE_CURRENT_CONVERSATION',

    INPUT: 'INPUT',
    // LOGIN: 'LOGIN',
    // LOGOUT: 'LOGOUT',
    // SIGNUP: 'SIGNUP',
    // CONNECT: 'CONNECT',
    // DISCONNECT: 'DISCONNECT',

    // CHAT_MESSAGE: 'CHAT_MESSAGE',
    LOAD_MESSAGE: 'LOAD_MESSAGE',
    ADD_MESSAGE: 'ADD_MESSAGE',

    // CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    LOAD_CONVERSATION_LIST: 'LOAD_CONVERSATION_LIST',

    
    // CREATE_CHANNEL: 'CREATE_CHANNEL',
    // LOAD_CHANNEL_LIST: 'LOAD_CHANNEL_LIST',

    // CHANGE_CURRENT_CHAT: 'CHANGE_CURRENT_CHAT',

    SENT_BROAD_CAST_MESSAGE: 'SENT_BROAD_CAST_MESSAGE',

    // vnit-service
    SENT_USER_INFO_MESSAGE: 'SENT_USER_INFO_MESSAGE',
    SENT_USER_INFO_STATUS: 'SENT_USER_INFO_STATUS',
    LOAD_USER_INFO_LIST: 'LOAD_USER_INFO_LIST'
   

};
 
